### ISSUE TITLE
[이슈]로그인 불가능한 부분 확인부탁드립니다.

### ISSUE THREAD

**Issue by diasm3** [ddang-ddang/front-end#4]
@piggggggggy @pol-dev-shinroo 

아래 파일부분에 IP가 기존 EC2로 설정되어있어서 로그인이 불가능했습니다.
아래부분을 **http://diasm.mooo.com:3000** 으로 변경 하시면 로그인 잘될겁니다 ^^
[파일링크](https://github.com/ddang-ddang/front-end/blob/a25e5d3ddbc0fd03982805b0d09c729071487731/src/shared/Link.js)

```javascript
export const BASE_URL = "http://52.221.217.61";
```

**Comment by pol-dev-shinroo** [comment]
로그인 확인했습니다!
